title: Lenzo
author: Debdut Goswami
email: projectlenzo@gmail.com
description: >-
  Lenzo is an online whiteboard application which enables user to stream on low bandwidth.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lenzo.tech" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

