# Generated by Django 3.1.4 on 2021-06-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0002_auto_20210108_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='duration',
            field=models.IntegerField(default=0, null=True, verbose_name='Duration (in sec)'),
        ),
        migrations.CreateModel(
            name='RoomPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='canvas.room')),
            ],
        ),
    ]
