# Generated by Django 3.1.4 on 2021-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0003_auto_20210622_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphotos',
            name='image',
            field=models.FileField(upload_to='photos'),
        ),
    ]
