# Generated by Django 3.1.4 on 2021-01-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("canvas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="End Time"),
        ),
        migrations.AddField(
            model_name="room",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Start Time"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="duration",
            field=models.IntegerField(default=0, verbose_name="Duration (in sec)"),
        ),
    ]
